(in-package :win-commands)

(macrolet ((command ()
	     `(eval-when (:compile-toplevel :load-toplevel :execute)
		(export (define-command adddrv))
		(export (define-command wappend :set-command "append"))
		(export (define-command attrib))
		(export (define-command wbreak :set-command "break"))
		(export (define-command call))
		(export (define-command cd))
		(export (define-command chcp))
		(export (define-command chdir))
		(export (define-command chev))
		(export (define-command chkdsk))
		(export (define-command clip))
		(export (define-command cls))
		(export (define-command cmd))
		(export (define-command color))
		(export (define-command command))
		(export (define-command comp))
		(export (define-command copy))
		(export (define-command date))
		(export (define-command del))
		(export (define-command deldrv))
		(export (define-command deltree))
		(export (define-command dir))
		(export (define-command diskcomp))
		(export (define-command diskcopy))
		(export (define-command doskey))
		(export (define-command echo))
		(export (define-command endlocal))
		(export (define-command erase))
		(export (define-command wexit :set-command "exit"))
		(export (define-command expand))
		(export (define-command fc))
		(export (define-command wfind :set-command "find"))
		(export (define-command findstr))
		(export (define-command for))
		(export (define-command forfiles))
		(export (define-command wformat :set-command "format"))
		(export (define-command goto))
		(export (define-command hostname))
		(export (define-command icacls))
		(export (define-command wif) :set-command "if")
		(export (define-command label))
		(export (define-command lh))
		(export (define-command loadhigh))
		(export (define-command md))
		(export (define-command mem))
		(export (define-command mkdir))
		(export (define-command mklink))
		(export (define-command mode))
		(export (define-command more))
		(export (define-command mountvol))
		(export (define-command move))
		(export (define-command path))
		(export (define-command pause))
		(export (define-command popd))
		(export (define-command wprint :set-command "print"))
		(export (define-command prompt))
		(export (define-command pushd))
		(export (define-command rd))
		(export (define-command recover))
		(export (define-command reg))
		(export (define-command rem))
		(export (define-command rename))
		(export (define-command replace))
		(export (define-command rmdir))
		(export (define-command robocopy))
		(export (define-command scandisk))
		(export (define-command wset :set-command "set"))
		(export (define-command setlocal))
		(export (define-command setver))
		(export (define-command setx))
		(export (define-command shift))
		(export (define-command wsort :set-command "sort"))
		(export (define-command start))
		(export (define-command wsubst :set-command "subst"))
		(export (define-command switch))
		(export (define-command sys))
		(export (define-command systeminfo))
		(export (define-command tasklist))
		(export (define-command taskkill))
		(export (define-command wtime :set-command "time"))
		(export (define-command timeout))
		(export (define-command title))
		(export (define-command tree))
		(export (define-command wtype :set-command "type"))
		(export (define-command tzutil))
		(exoprt (define-command ver))
		(export (define-command verify))
		(export (define-command vol))
		(export (define-command where))
		(export (define-comamnd whoami))
		)))
  (command))
