(in-package :win-commands)

(macrolet ((command ()
	     `(eval-when (:compile-toplevel :load-toplevel :execute)
		(export (define-command adddrv))
		(export (define-command wappend :set-command "append"))
		(export (define-command attrib))
		(export (define-command wbreak :set-command "break"))
		(export (define-command call))
		(export (define-command cd))
		(export (define-command chcp))
		(export (define-command chdir))
		(export (define-command chev))
		(export (define-command chkdsk))
		(export (define-command clip))
		(export (define-command cls))
		(export (define-command cmd))
		(export (define-command color))
		(export (define-command command))
		(export (define-command comp))
		(export (define-command copy))
		(export (define-command date))
		(export (define-command del))
		(export (define-command deldrv))
		(export (define-command deltree))
		(export (define-command dir))
		(export (define-command diskcomp))
		(export (define-command diskcopy))
		(export (define-command doskey))
		(export (define-command echo))
		(export (define-command endlocal))
		(export (define-command erase))
		(export (define-command wexit :set-command "exit"))
		(export (define-command expand))
		)))
  (command))
